version: '3'

services:
  springboot:
    build: .
    container_name: runmate-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - project-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      # 기본 슈퍼유저로 initdb 수행
      # POSTGRES_USER, POSTGRES_DB 는 지정하지 않습니다.
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      # initdb 후 init-user-db.sh 를 실행
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - project-net
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - project-net

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - springboot
    networks:
      - project-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email kimh0414@gmail.com --agree-tos --no-eff-email -d k12d107.p.ssafy.io
    depends_on:
      - nginx

networks:
  project-net:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root: