spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.runhwani.runmate.domain

management:
  endpoints:
    web:
      exposure:
        include: health,info
